// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZVZC-tc3MsYNONS-zVT9H4Qa9q8YD054',
    appId: '1:253718284138:web:a2e8e024c6122f9c998713',
    messagingSenderId: '253718284138',
    projectId: 'kasir-pro-a9442',
    authDomain: 'kasir-pro-a9442.firebaseapp.com',
    storageBucket: 'kasir-pro-a9442.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxuuYKT5C27R6ZFh5M-eT_B-0i-OzR7aI',
    appId: '1:253718284138:android:297e4016281ed85c998713',
    messagingSenderId: '253718284138',
    projectId: 'kasir-pro-a9442',
    storageBucket: 'kasir-pro-a9442.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS3gc-urKfI2k3Ht6G_zkz6tELFc899C0',
    appId: '1:253718284138:ios:29def54f5e8e427c998713',
    messagingSenderId: '253718284138',
    projectId: 'kasir-pro-a9442',
    storageBucket: 'kasir-pro-a9442.firebasestorage.app',
    iosBundleId: 'com.kasirpro.kasirProMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS3gc-urKfI2k3Ht6G_zkz6tELFc899C0',
    appId: '1:253718284138:ios:29def54f5e8e427c998713',
    messagingSenderId: '253718284138',
    projectId: 'kasir-pro-a9442',
    storageBucket: 'kasir-pro-a9442.firebasestorage.app',
    iosBundleId: 'com.kasirpro.kasirProMobile',
  );
}
